bcmdhd: kstat_irqs is a struct now (v6.10 compatibility)
Linux commit [1] has changed struct irq_desc::kstat_irqs from unsigned
int to struct irqstat.

This breaks compilation of this driver:

    .../bcmdhd4389/dhd_linux.c:21746:21: error: incompatible operand types ('typeof (*((desc->kstat_irqs)))' (aka 'struct irqstat') and 'int')
     21746 |                         desc->kstat_irqs ? *per_cpu_ptr(desc->kstat_irqs, i) : 0);
           |                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ~
    1 error generated.

Update the code accordingly.

Note that we don't need to test for desc->kstat_irqs != NULL because it
is directly part of desc.

Test: TH
Bug: 353704691
Change-Id: I446f44036fbb76f43dd1adf9085785fd362d360c
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>