bcmdhd: struct pci_driver::node is gone (v6.8 compatibility)
Linux commit [1] has removed struct pci_driver::node.

This causes this OOT pixel driver to fail compilation:
    .../wlan/bcmdhd4389/dhd_pcie_linux.c:273:26: error: no member named 'node' in 'struct pci_driver'
      273 |         node:           {&dhdpcie_driver.node, &dhdpcie_driver.node},
          |                           ~~~~~~~~~~~~~~ ^
    .../wlan/bcmdhd4389/dhd_pcie_linux.c:273:48: error: no member named 'node' in 'struct pci_driver'
      273 |         node:           {&dhdpcie_driver.node, &dhdpcie_driver.node},
          |                                                 ~~~~~~~~~~~~~~ ^
    2 errors generated.

This hasn't been needed for more than 20 years, so just remove the
assignment here.

Test: TH
Bug: 331358284
Change-Id: Idbc6f06ac5e2db0821d5a0e1c9632bacaf52f818
Signed-off-by: André Draszik <draszik@google.com>